#!/bin/bash

#xdg-settings set default-web-browser qutebrowser


source /home/aghiles/Aghiles/tool/shell/system/export


# Config
ln -sf $TOOLPATH/config/*/* /home/aghiles/.config/
ln -sf $TOOLPATH/config/system/.* /home/aghiles/
chmod -R u+x ~/.local/share/nautilus/scripts
chmod -R u+x ~/.local/share/qutebrowser/userscripts

# Scripts
chmod -R u+x $TOOLPATH/shell


# Program
ln -sf /media/aghiles/Aghiles $READINGPATH
chmod -R u+x $PROGRAMPATH/*

#sudo ln -s /home/aghiles/Aghiles/Tool/scripts/targetos /usr/bin


# Tools
ln -sf $TOOLSPATH/n-ns-3/ns-3-dev/examples/lorawan $SIMULATIONPATH/ns3/src1
ln -sf $TOOLSPATH/n-ns-3/ns-3-dev/examples/aghiles $SIMULATIONPATH/ns3/src2
ln -sf $TOOLSPATH/n-ns-3/ns-3-dev/src/lorawan $SIMULATIONPATH/ns3/lib

chmod -R u+x $TOOLSPATH/c-matlab/bin

chmod -R u+x $TOOLSPATH/r-zotero/zotero $TOOLSPATH/r-zotero/zotero-bin
#sudo mv /usr/bin/pdftotext /usr/bin/pdftotext2
#sudo ln -sf $TOOLSPATH/zotero/pdftotext /usr/bin/pdftotext

sudo ln -sf /media/aghiles/Aghiles $READINGPATH/doc
