#!/bin/bash

#xdg-settings set default-web-browser qutebrowser


source /home/aghiles/Aghiles/tool/shell/zsh/export


# Config
ln -sf $TOOLPATH/config/*/* /home/aghiles/.config/
ln -sf $TOOLPATH/config/home/.* /home/aghiles/
chmod -R u+x ~/.local/share/nautilus/scripts
chmod -R u+x ~/.local/share/qutebrowser/userscripts

# Scripts
chmod -R u+x $TOOLPATH/shell


# Program
ln -sf /media/aghiles/Aghiles $READINGPATH
chmod -R u+x $PROGRAMPATH/engineering/*


# Tools
ln -sf $TOOLSPATH/ns-3/ns-3/examples/lorawan $PROGRAMPATH/simulation/ns3/src1
ln -sf $TOOLSPATH/ns-3/ns-3/examples/aghiles $PROGRAMPATH/simulation/ns3/src2
ln -sf $TOOLSPATH/ns-3/ns-3/src/lorawan $PROGRAMPATH/simulation/ns3/lib

chmod -R u+x $TOOLSPATH/matlab/bin

chmod -R u+x $TOOLSPATH/zotero/zotero $TOOLSPATH/zotero/zotero-bin
#sudo mv /usr/bin/pdftotext /usr/bin/pdftotext2
#sudo ln -sf $TOOLSPATH/zotero/pdftotext /usr/bin/pdftotext

sudo ln -sf /media/aghiles/Aghiles $READINGPATH/doc
