#!/bin/bash

#https://clang.llvm.org/docs/ClangFormatStyleOptions.html

sed -Ei 's/  /\t/g' *.c *.cpp *.cc *.h
for c in *.cc; do script.sed < $c > /tmp/zyzcc.cc; /bin/cp -f /tmp/zyzcc.cc $c; done
for c in *.h; do script.sed < $c > /tmp/zyzcc.h; /bin/cp -f /tmp/zyzcc.h $c; done
sed -Ezi 's/\n[\n \t]*\n/\n/g' *.c *.cpp *.cc *.h


clang-format -style=llvm -dump-config > .clang-format

sed -Ei 's/ColumnLimit:[ \t]*80/ColumnLimit:     999999/g' .clang-format
sed -Ei 's/ReflowComments:[ \t]*true/ReflowComments:  false/g' .clang-format
sed -Ei 's/KeepEmptyLinesAtTheStartOfBlocks:[ \t]*true/KeepEmptyLinesAtTheStartOfBlocks: false/g' .clang-format
sed -Ei 's/Penalty([^:]*:).*/Penalty\1 999999/g' .clang-format


clang-format -style=file -i *.c *.cpp *.cc *.h


