#!/bin/bash

tt="$1"

ffile=/tmp/ij

grep -Po -r -i ".{0,115}$1.{0,115}" */*.txt  > $ffile


#grep -Po -r "[A-Z].*?$1.*?\." */.zotero-ft-cache |  sed -r -e 's/\/.zotero-ft-cache//g' | awk -v d="$1" 'BEGIN{IGNORECASE=1}{ gsub("^........:", "\033[1;31m&\033[0m"); gsub(d, "\033[1;31m&\033[0m"); print }'

sed -i 's|/|plmkijh|g' $ffile

#http://unix.stackexchange.com/questions/209025/ddg#209052





dir=$(mktemp -d)
sed 's|:|/|g' $ffile | while read -r line; do mkdir -p "$dir/$line"; done
(cd "$dir"; tree) | sed 's|plmkijh|/|g' | sed 's|\.txt|\.pdf|g' | awk -v d="$1" 'BEGIN{IGNORECASE=1}{ gsub("^.*.pdf", "\033[1;34m&\033[0m"); gsub(d, "\033[1;31m&\033[0m"); print }'
rm -r "$dir"


