#!/bin/bash


find -name "* *" -type d | rename 's/ /_/g'
find -name "* *" -type f | rename 's/ /_/g'

find . -type f -name '*.*' -print0 | 
while IFS= read -r -d '' file; do
	sed -i '1 i\#!/usr/bin/env Rscript\nDATAPATH <- Sys.getenv("DATAPATH")\n' "$file"
	sedx "scan\(\"[\.\/]+res\/(.*)\"" "scan\(paste\(DATAPATH,\"\1\",sep=\"\/\"\)" "$file"
#    printf '%s\n' "$file"
done




#find . -type f -name "*.r" -exec sedx "scan\(\"[\.\/]+res\/(.*)\"" "scan\(paste\(DATAPATH,\"\1\",sep=\",\"\)" {} +
