#!/bin/sh

for file in "$@"; do 
	directory=`dirname "$file"`
	filename=`basename "$file"`
	echo $filename
	extension="${filename##*.}"
	filename="${filename%.*}"
	pdftotext "$file" "$directory/$filename.txt"; 
done


