#!/bin/sh

maim_dir=$HOME
DATE="$(date '+%Y-%m-%d_%H:%M:%S')"
maim_file="${DATE}_screenshot.png"

if ! [ -d $maim_dir ]; then
	mkdir -p $maim_dir
fi

if ! [ -z "$2" ]; then
    cmd="maim -m 3 -d $2"
else
    cmd='maim -m 3'
fi

case "$1" in
	--desk|-d|$NULL)
		cd $maim_dir
	        $cmd $maim_file &&
		sleep .5 &&
		notify-send "screenshot has been saved in $maim_dir"
		;;
	--window|-w)
		cd $maim_dir
    $cmd -i $(xdotool getactivewindow) $maim_file &&
		sleep .5 &&
		notify-send "screenshot has been saved in $maim_dir"
		;;
	--select|-s)
		cd $maim_dir
		notify-send 'select an area for the screenshot' &
		$cmd -s $maim_file &&
		sleep .5 && notify-send "screenshot has been saved in $maim_dir"
		;;
	--help|-h)
		echo "
available options:
-d | --desk    full screen
-w | --window  active window
-s | --select  selection
-h | --help    display this information

The -d or -w options can be used with a delay
by adding the number of seconds, like for example:
'i3-maim -w 5'

Default option is 'full screen'.

The file destination can be set in ${_conf}.
Default is $maim_dir
"
		;;
	*)
		echo "
== ! i3-maim: missing or wrong argument ! ==

available options:
-d | --desk    full screen
-w | --window  active window
-s | --select  selection
-h | --help    display this information

Default option is 'full screen'.

The file destination can be set in ${_conf}.
Default is $maim_dir
"

        exit 2
esac

exit 0
