#!/bin/sh

account1="https://esdxfvgijhg@github.com/esdxfvgijhg"
account2="https://esxdwqzpml@github.com/esxdwqzpml"
localx="/media/aghiles/Aghiles"



#cd $ADMINPATH    && git remote add admin      $localx/admin
#cd $TOOLPATH     && git remote add tool       $localx/tool

cd $PROGRAMPATH  && git remote add cod        $account1/cod.git
cd $TEACHINGPATH && git remote add ece        $account1/ece.git
#cd $READINGPATH  && git remote add doc        $accoun2/doc.git
cd $WRITINGPATH  && git remote add txt        $account1/txt.git
cd $TOOLPATH     && git remote add tool       $account1/tool.git


