#!/bin/bash

find . -size +100M | cat > .gitignore

echo "
tools
config/home/.local/share/data
config/home/.local/share/Trash
tools
" >> .gitignore

filename=`basename "$PWD"`

git add -v .
git commit -m "commit"
git push -u -f $filename master

echo $PWD
read
