#!/bin/bash

showusage() {
  echo "Usage:"
  echo "  screen.sh [options] main-display"
  echo ""
  echo "Options:"
  echo "  -l <display>  Display to be used to the left of main-display"
  echo "  -r <display>  Display to be used to the right of main-display"
  echo "  -p            Rotate the display on the sides of the main-display to portrait to the right"
  echo "  -P            Rotate the display on the sides of the main-display to portrait to the left"
  echo "  -h            Show this screen."
}

disablerest() {
  cmd=$1
  for line in $(xrandr -q|grep '\bconnected\b'|cut -d' ' -f1); do
    if [[ ("$line" != "$middle") && ("$line" != "$left") && ("$line" != "$right") ]]; then
      cmd="$cmd --output $line --off"
    fi
  done
  echo "$cmd"
}

rotate="normal"
while getopts "l:r:hpP" opt; do
  case ${opt} in
    l )
      left="$OPTARG"
      ;;
    r )
      right="$OPTARG"
      ;;
    p )
      rotate="right"
      ;;
    P )
      rotate="left"
      ;;
    h )
      showusage
      exit 0
      ;;
    \? )
      echo "Invalid Option: -$OPTARG" 1>&2
      showusage
      exit 1
      ;;
  esac
done
shift $((OPTIND - 1))

middle="$1"
cmd="xrandr "

if [[ ("$middle" != "") && ($(xrandr -q |grep $middle\ con)) ]]; then
  cmd="$cmd --output $middle --auto --rotate normal"

  if [[ ("$left" != "") && ($(xrandr -q |grep $left\ con)) ]]; then
    cmd="$cmd --output $left --auto --rotate $rotate --left-of $middle"
  fi

  if [[ ("$right" != "") && ($(xrandr -q |grep $right\ con)) ]]; then
    cmd="$cmd --output $right --auto --rotate $rotate --right-of $middle"
  fi

  cmd=$(disablerest "$cmd")
else
  echo "Falling back to only laptop display" 1>&2

  middle="LVDS-1"

  cmd=$(disablerest "$cmd")

  if [[ ("$left" != "") && ($(xrandr -q |grep $left\ con)) ]]; then
    cmd="$cmd --output $left --off"
  fi

  if [[ ("$right" != "") && ($(xrandr -q |grep $right\ con)) ]]; then
    cmd="$cmd --output $right --off"
  fi

  cmd="$cmd --output LVDS-1 --auto"
fi

echo $cmd
eval $cmd

$HOME/.config/Scripts/polybarlaunch
$HOME/.config/Scripts/setbackground
$HOME/.config/Scripts/remaps
