#!/bin/bash


if [ $# -eq 0 ]; then
  echo -e "No arguments specified. Usage:\ntransfer /tmp/test.md";
  exit 1;
fi
tmpfile=$( mktemp -t transferXXX );
if tty -s; then
  basefile=$(basename "$1" | sed -e 's/[^a-zA-Z0-9._-]/-/g');
  curl --progress-bar --upload-file "$1" "https://transfer.sh/$basefile" >> $tmpfile;
else
  curl --progress-bar --upload-file "-" "https://transfer.sh/$1" >> $tmpfile ;
fi;
cat $tmpfile;
command -v xclip > /dev/null && cat $tmpfile | xclip -selection clipboard;
command -v qrencode > /dev/null && cat $tmpfile | qrencode -t UTF8i;
rm -f $tmpfile;
