#!/bin/bash
# Bash Menu Script Example

PS3='Please enter your choice: '
options=("Contiki" "Riot" "Option 3" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Contiki")
            compile-contiki "$@"
            ;;
        "Riot")
            compile-riot "$@"
            ;;
        "Option 3")
            echo "you chose choice $REPLY which is $opt"
            ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
