#!/usr/bin/env sh

# This script will compile or run another finishing operation on a document. I
# have this script run via vim.
#
# Compiles .tex. groff (.mom, .ms), .rmd, .md.  Opens .sent files as sent
# presentations.  Runs scripts based on extention or shebang

file=$(readlink -f "$1")
dir=$(dirname "$file")
base="${file%.*}"

cd "$dir" || exit


#mypath=`realpath "$0"`
#directory=`dirname "$mypath"`
#filename=`basename "$directory"`
#cd "$directory"


case "$file" in
	*\.ms) refer -PS -e "$file" | groff -me -ms -kept -T pdf > "$base".pdf ;;
	*\.mom) refer -PS -e "$file" | groff -mom -kept -T pdf > "$base".pdf ;;
	*\.[0-9]) refer -PS -e "$file" | groff -mandoc -T pdf > "$base".pdf ;;
	*\.rmd) echo "require(rmarkdown); render('$file')" | R -q --vanilla ;;
	*\.tex) compile-latex "$file" ;;
	*\.md) pandoc "$file" --pdf-engine=xelatex -o "$base".pdf ;;
	*config.h) sudo make install ;;
        *\.c) cc "$file" -o "$base" && "$base" ;;
	*\.py) python "$file" ;;
	*\.go) go run "$file" ;;
	*\.sent) setsid sent "$file" 2>/dev/null & ;;
	*) sed 1q "$file" | grep "^#!/" | sed "s/^#!//" | xargs -r -I % "$file" ;;
esac


#cd "$dir" || exit

#function pdfpcCleanup {
#  [[ -e "$base".pdfpc ]] && sed -i 's/\\\\/\n/g' "$base".pdfpc && sed -i 's/\\par/\n\n/g' "$base".pdfpc
#}

#case "$file" in
#  *\.uml|*\.pu) plantuml "$file" ;;
#  *\.gv|*\.dot) dot -Tpng "$file" -o "$base".png ;;
#  *\.ms) refer -PS -e "$file" | groff -me -ms -kejpt -T pdf > "$base".pdf ;;
#  *\.mom) refer -PS -e "$file" | groff -mom -kejpt -T pdf > "$base".pdf ;;
#  *\.rmd) echo "require(rmarkdown); render('$file')" | R -q --vanilla && pdfpcCleanup ;;
#  *\.tex) latexmk -synctex=1 --pdf "$file" && [[ -e "$base".pdfpc ]] && pdfpcCleanup ;;
#  *\.md) if [[ -e "$base"_template.tex ]] ; then pandoc --template "$base"_template.tex "$file" --filter pandoc-citeproc --variable urlcolor=blue -o "$base".pdf; else  pandoc "$file" --filter pandoc-citeproc --variable urlcolor=blue -o "$base".pdf; fi ;;
#  *config.h) make && sudo make install ;;
#  *\.c) gcc "$file" -o "$base" && "$base" ;;
#  *\.py) python "$file" ;;
#  *\.go) go run "$file" ;;
#  *\.shortcuts) genshortcuts ;;
#esac
