#! /bin/bash


#mypath=`realpath $0`
#directory=`dirname $mypath`
#folder=`basename $directory`
#filename=`basename $0`
#filename=0
#folder=".main"

#ty="$folder.sublime-project"

subl -n --project $WRITINGPATH/CV/.cl.sublime-project $WRITINGPATH/CV/cl.tex

