#!/bin/sh

# We need to remove the stupid "file://" that Evince puts in front of the file name
# Notice the wild quoting: we need to interpolate $SUBLIME
# In the end, EDITORCMD should be of the form:
#
# f=%f; sublime-text "${f#file://}:%l"
#
# where sublime-text is the name of the sublime-text binary
EDITORCMD="f=\"%f\"; subl \"\${f#file://}:%l\""
#EDITORCMD="vim --servername 'VIM' --remote-silent '+%l<Enter>:match Search /\%%ll/' %f"
#EDITORCMD="nvim '+%l<Enter>:match Search /\%%ll/' \"%f\""
#EDITORCMD="emacsclient -a \`\` --no-wait +%l \"%f\""
#EDITORCMD="gvim --servername somepdf --remote-silent '+%l<Enter>' \"%f\""


PDFFILE="$1"

if [ -f "$PDFFILE" ];then
	# danke an Feuerfieber
	# http://forum.ubuntuusers.de/topic/evince-synctex-vim-emacs-scite-lyx-kile-editor/#post-2841828
	if [ -f "${PDFFILE%%.pdf}.synctex.gz" ];then
		# we change the cwd to this directory, so this should work
		# also note that we stick in 'python' because the script file need not be executable
		evince_backward_search "$PDFFILE" "$EDITORCMD"&
		BACKWARD_SEARCH_PID=$!
		echo $BACKWARD_SEARCH_PID
	fi
fi

/usr/bin/evince "$@"

if [ "$BACKWARD_SEARCH_PID" ];then
	echo "Killing $BACKWARD_SEARCH_PID"
	kill $BACKWARD_SEARCH_PID
fi
