#!/usr/bin/env sh
# Gives a dmenu prompt to search DuckDuckGo.
# Without input, will open DuckDuckGo.com.
# URLs will be directly handed to the browser.
# Anything else, it search it.
browser=${BROWSER:-firefox}

pgrep -x dmenu && exit

choice=$(echo "🦆" | dmenu -i -p "Google:") || exit 1

if [ "$choice" = "🦆"  ]; then
    $browser "https://www.google.com"
else
    if echo "$choice" | grep "^(http:\/\/|https:\/\/)?[a-zA-Z0-9]+\.[a-zA-Z]+(/)?.*$"; then
        $browser "$choice"
    else
        $browser "https://www.google.com/search?q=$choice&t=ffab&atb=v1-1"
    fi
fi
