#!/bin/bash


# some more ls aliases
#alias ll='ls -l'
#alias la='ls -A'
#alias l='ls -CF'

## exceptions to auto-correction
#alias bundle='nocorrect bundle'
#alias cabal='nocorrect cabal'
#alias man='nocorrect man'
#alias mkdir='nocorrect mkdir'
#alias mv='nocorrect mv'
#alias stack='nocorrect stack'
#alias sudo='nocorrect sudo'


alias ble="bluetoothctl"
alias airpods="ble connect $airpods"
alias audio="pavucontrol"

alias inst="$TOOLPATH/shell/install"

alias installx="sudo apt -y install"
alias vgh="convert -delay 12 -loop 0 *.jpg animated.gif"
alias ap="ansible-playbook"
alias assh="autossh -M 0"
alias aud="pulsemixer"
alias bcdl="bandcamp-dl"
alias ccat="highlight --out-format=ansi"
alias ccat="highlight --out-format=xterm256"
alias cchat="mkdir -p ~/Logs/irc ; sic -h chat.freenode.com | tee ~/Logs/irc/$(date +%m%d)$(date +%H%M)chat.log | lolcat"
alias chat="mkdir -p ~/Logs/irc ; sic -h chat.freenode.com | tee ~/Logs/irc/$(date +%m%d)$(date +%H%M)chat.log"
alias d="amixer sset Master 2-%"
alias df="df -h"
alias diff="diff --color=auto"
alias dnsflush="sudo dscacheutil -flushcache"
alias dus="du -hd 1 | sort -h"
alias ffmpeg="ffmpeg -hide_banner"
alias fs="findstring"
alias jabber="mcabber -f ~/.config/mcabber/mcabberrc"
alias jpegoptim="for i (*.jpg) mozjpeg -copy none -optimize -scans ~/dotfiles/other/scans.txt -outfile $i $i"
alias jpg25="mogrify -format jpg -resize 25% -strip -quality 80 *.jpg"
alias jpg50="mogrify -format jpg -resize 50% -strip -quality 80 *.jpg"
alias lock="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
alias lsexts="find . -type f -name \"*.*\" -printf \"%f\n\"|sed \"s/.*\.\([^.]*\)$/\1/\"|sort|uniq"
alias lsp="pacman -Qett --color=always | less"
alias mapscii="telnet mapscii.me"
alias mcabber="mcabber -f ~/.config/mcabber/mcabberrc"
alias mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"
alias mus="ncmpcpp"
alias npmre="rm -f package-lock.json && rm -rf node_modules && npm install"
alias orphans="pacman -Qdt"
alias pacrepo="sudo reflector -l 20 -f 10 --save /etc/pacman.d/mirrorlist"
alias pacu="sudo pacman -Syu --noconfirm"
alias path="echo -e "${PATH//:/\n}""
alias png25="mogrify -format png -resize 25% -strip -quality 80 *.png"
alias png50="mogrify -format png -resize 50% -strip -quality 80 *.png"
alias progs="pacman -Qet"
alias psref="gpg-connect-agent RELOADAGENT /bye"
alias pwgen="genpw"
alias reddit="rtv"
alias rs="replacespaces"
alias speedtest="speedtest | lolcat"
alias te="timeentry"
alias tf="terraform"
alias trem="transmission-remote"
alias u="amixer sset Master 2+%"
alias udu="udiskie-umount"
alias upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks"
alias upgr="neofetch && sudo pacman -Syyu --noconfirm && unix && notify-send \"📦 Update complete.\" && echo Update complete. | figlet"
alias webimg="mogrify -format jpg -resize 1600x1600 -strip -quality 70"
alias xpull="syncworkflow down"
alias xpush="syncworkflow up"
alias yre="rm -f yarn.lock && rm -rf node_modules && yarn"
alias yta="yt -x -f bestaudio/best"
alias ytdl="youtube-dl"
alias yt="youtube-dl --add-metadata -i -o \"%(upload_date)s-%(title)s.%(ext)s\""
alias YT="youtube-viewer"




# DISPLAY
alias blank="DISPLAY=:0 xset dpms force off"
alias zap="DISPLAY=:0 xwarppointer relpos 10 10"



# APP
alias zotero=$TOOLSPATH/zotero/zotero
alias mu="neomutt"
alias office="cd ~ && mbsync -a && mu index --maildir ~/Mail && vdirsyncer sync"

alias matlab="LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25 $TOOLSPATH/matlab/bin/matlab"
alias www="$BROWSER"
alias calcurse="calcurse -C ~/.config/calcurse/ -D ~/.config/calcurse/"
alias news="newsboat"
alias x="sxiv -ft *"
alias term="tilix"


#Install
alias mi="clear && sudo make clean install"


alias aptup="sudo apt update && sudo apt upgrade && sudo apt autoremove"
alias mkd="mkdir -p"
alias ka="killall"
alias q="exit"
alias o="xdg-open"
alias ssh="TERM=xterm-256color ssh"
alias passwd_gen="openssl rand -base64 32"
alias ref="shortcuts >/dev/null; source ~/.config/shortcutrc"
alias newnet="sudo systemctl restart NetworkManager"
alias systemctl="sudo systemctl"
alias rf="source ~/.bashrc"
alias pushkey="ssh-copy-id -i ~/.ssh/id_rsa.pub"
alias netcfg="sudo netcfg"
alias netctl="sudo netctl"
alias atltime="sudo timedatectl set-timezone America/New_York"
alias journalctl="sudo journalctl"
alias apt="sudo apt"
alias reboot="checkout ; sudo reboot now"
alias sdn="checkout ; sudo shutdown -h now"
alias disks="gnome-disks"
alias clip="nc localhost 8377"


alias eclipse=$TOOLSPATH/eclipse/eclipse/eclipse

alias trans='trans -b -t fr'
alias xd='tracker tag -ts'


# GREP
alias crep="grep --color=always"
alias grep="grep --color=auto"
alias rawcode="grep -cv ^#\|^$"

# LS
alias lal="ls -aFl"
alias la="ls -aF"
alias ll="ls -lF"
alias l="ls -alGp"
alias lsds="ls -d .*" # ls dot files only
alias lsa="ls -alGp"
alias ls="ls -Fc --color=auto --group-directories-first"


# NPM
alias nb="npm run build"
alias np="npm run production"
alias nr="npm run"
alias ns="npm start"


# XINPUT
alias xi="xinput       set-prop 8 \"Device Enabled\" 1 && xinput set-prop 10 \"Device Enabled\" 1"
alias no_touch="xinput set-prop \"SynPS/2 Synaptics TouchPad\" \"Device Enabled\" 0"
alias nxi="xinput      set-prop 8 \"Device Enabled\" 0 && xinput set-prop 10 \"Device Enabled\" 0"


# MPC
alias n="mpc -h $_SECRET_MPD_HOST --no-status next; np"
alias np="mpc --format \"%title% - %artist% #[%album%#]\" | head -n1"
alias p="mpc -h $_SECRET_MPD_HOST --no-status prev; np"
alias P="mpc -h $_SECRET_MPD_HOST --no-status toggle; np"
alias s="mpc -h $_SECRET_MPD_HOST --no-status stop; np"
alias addall="mpc update > /dev/null && mpc --no-status clear && mpc ls | mpc --no-status add && mpc --no-status play; np"


#EDITOR
alias a="tmux a"
alias tmux="tmux -f ~/.config/tmux/tmux.conf"
alias t="tmux -u -2"
alias ta="tmux -u attach"
alias v="$EDITOR"
alias vdiff="$EDITOR -d"
alias vi=$EDITOR
alias vim=$EDITOR
alias vimdiff="$EDITOR -d"
alias cfa="$EDITOR ~/.config/aliasrc"
alias cfb="$EDITOR ~/.bashrc"
alias cfB="$EDITOR ~/.config/i3blocks/config"
alias bd="$EDITOR ~/.config/bmdirs"
alias bf="$EDITOR ~/.config/bmfiles"
alias cfd="$EDITOR ~/.Xdefaults"
alias cfi="$EDITOR ~/.config/i3/config"
alias cfk="$EDITOR ~/.config/sxhkd/sxhkdrc"
alias cfm="$EDITOR ~/.config/mutt/muttrc"
alias cfmb="$EDITOR ~/.config/ncmpcpp/bindings"
alias cfmc="$EDITOR ~/.config/ncmpcpp/config"
alias cfn="$EDITOR ~/.config/newsboat/config"
alias cfu="$EDITOR ~/.config/newsboat/urls"
alias cfv="$EDITOR ~/.config/nvim/init.vim"
alias cfz="$EDITOR ~/.zshrc"
alias cv="$EDITOR ~/Documents/LaTeX/cv.tex"
alias e="$EDITOR"
alias eb="$EDITOR ~/Documents/LaTeX/uni.bib"
alias er="$EDITOR ~/Documents/referbib"
alias vim="vim -u ~/.config/vim/init.vim"
alias v="vim"
alias sv="sudo vim"
alias magit="nvim -c MagitOnly"
alias note="vim ~/Documents/Note.md"
alias css=$EDITOR
alias scss=$EDITOR
alias js=$EDITOR
alias html=$EDITOR
alias md=$EDITOR
alias txt=$EDITOR

#CD
alias vv="cd ~/Videos && ls -a"
alias .....="cd ../../../.."
alias ....="cd ../../.."
alias ...="cd ../.."
alias ..="cd .."
alias ~="cd ~"
alias cf="cd ~/.config && ls -a"
alias D="cd ~/Downloads && ls -a"
alias h="cd ~/ && ls -a"
alias m="cd ~/Music && ls -a"
alias mn="cd /mnt && ls -a"
alias n="cd ~/Documents/networks && ls -a"
alias P="cd ~/Projects && ls -a"
alias pp="cd ~/Pictures && ls -a"
alias s="cd ~/.local/bin && ls -a"
alias web="cd ~/Sites && ls"
alias rep="cd ~/Repositories && ls"
alias dot="cd ~/Dotfiles && ls"

#GIT
alias gd="git diff"
alias gf="git-flow"
alias g="git"
#alias ggpl="git pull origin $(current_branch)"
#alias ggpnp="git pull origin $(current_branch) && git push origin $(current_branch)"
#alias ggps="git push origin $(current_branch)"
#alias gmo="$EDITOR $(git ls-files -m)"
alias gs="git status"
alias gsmu="git submodule init && git submodule update"
alias gsmuu="git submodule foreach git pull origin master"
alias gst="git status"
alias gua="git remote | xargs -L1 git push --all"


## default applications
#alias -s c=nvim
#alias -s cpp=nvim
#alias -s java=nvim
#alias -s md=nvim
#alias -s tex=nvim
#alias -s log="less -MN"

# aliases for Tmux
alias tmux='tmux -2'
alias ta='tmux attach -t'
alias tnew='tmux new -s'
alias tls='tmux ls'
alias tkill='tmux kill-session -t'
alias mux='tmuxinator'
alias tmuxlayout='tmux list-windows|sed "s/^.*\[layout \(.*\)\] @.*$/\1/"'


# email aliases
alias m='neomutt'
alias msmtpqm='msmtpq --q-mgmt'
# calendar aliases
alias kl='khal'
alias ikl='ikhal'
alias kla='khal -c $HOME/.config/khal/academicconfig'
alias ikla='ikhal -c $HOME/.config/khal/academicconfig'

# addressbook aliases
alias kd='khard'
alias kdd='khard details'

# sync aliases
alias oimap='offlineimap'
alias vd='vdirsyncer'
alias vds='vdirsyncer sync'

# various app aliases
alias nb='newsboat'
alias nf='neofetch'
alias yt="mpsyt"
alias vi='nvim'
alias vim='nvim'
alias arc='aria2c'
alias sc='scim'

# pass aliases
alias pshow='pass show'
alias pedit='pass edit'
alias pupdate='pass update -p'
alias ptail='pass tail'
alias ptedit='pass tailedit'


# git aliases
alias g='git'
alias gb='git branch'
alias gcm='git commit --message'
alias gco='git checkout'
alias gf='git fetch'
alias gfc='git clone'
alias gfm='git pull'
alias gia='git add'
alias gp='git push'
alias gr='git rebase'
alias gS='git submodule'
alias gSa='git submodule add'
alias gSi='git submodule init'
alias gSI='git submodule update --init --recursive'
alias gws='git status --short'
alias gwS='git status'
alias glv="git log --graph --pretty=format:'%h - %d %s (%cr) <%an>' | nvim -R -c 'set hidden nowrap keywordprg=:enew\ \|\ terminal\ \git\ --no-pager\ show | nnoremap q :bd!<cr>' -"
alias db='popd > /dev/null && dirs -v'
alias dv='dirs -v'
alias httpstart='python -m http.server 8080'
alias dmenu='dmenucolor'
alias systemctlu='systemctl --user'

# cp -> rsync
alias cp='rsync -ah --partial --inplace --info=progress2'

alias pip='pip3'
alias Rupdate='sudo Rscript -e '"'"'update.packages(checkBuilt=TRUE, ask=FALSE, repos="https://cran.rstudio.com")'"'"
alias chmox='chmod +x'
alias maketags='ctags -R .'
alias l='ls'
alias sl='ls'
alias ll='ls -alF'
alias la='ls -A'
alias ..='cd ..'
alias ...='cd ../..'
alias todo='vi $HOME/.todo.md'
alias makescript="fc -rnl | head -1 >"
alias histg='history | grep'
alias cmount='mount | column -t'
alias meminfo='free -m -l -t'
alias psg='ps aux | grep'
alias ipinfo="curl ifconfig.me && curl ifconfig.me/host"
alias alert='notify-send -i "$([ $? = 0 ] && echo terminal || echo error)" "$(cat $HOME/.zsh_history|tail -n1|cut -d'\'';'\'' -f2-|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias fuck='sudo /usr/bin/zsh -c "$(fc -rnl| head -1)"'


# LaTeX Template aliases
alias txa="filetemplate $HOME/Documents/latex/templates/article.tex"
alias txb="filetemplate $HOME/Documents/latex/templates/beamer.tex"
alias txm="filetemplate $HOME/Documents/latex/templates/mla.tex"

# Markdown Template aliases
alias mda="filetemplate $HOME/Documents/markdown/templates/article.md"
alias mdb="filetemplate $HOME/Documents/markdown/templates/beamer.md"
alias rmda="filetemplate $HOME/Documents/markdown/templates/article.rmd"
alias rmdb="filetemplate $HOME/Documents/markdown/templates/beamer.rmd"



# unused aliases
#alias gohome='sudo openvpn --script-security 2 --config $HOME/.openvpn/halter_home.ovpn'
#alias dataBackup='$HOME/backupScript/backup.sh'
#alias dataBackupUmount='$HOME/backupScript/backup.sh && sleep 5 && sudo umount /dev/sdd1'



#
# Command aliases
#

alias ....='cd ../..'
alias :e=vim
alias :qa=exit
alias :sp='test -n "$TMUX" && tmux split-window'
alias :vs='test -n "$TMUX" && tmux split-window -h'
alias :wq=exit
alias a=ag
alias b=bundle
alias be='bundle exec'
alias cd..='cd ..'
alias clip='nc -U ~/.clipper.sock'
alias d='hash -d'
alias e=exit
alias f='find . -name'
alias g=git
alias groot='cd $(git rev-parse --show-toplevel 2> /dev/null || echo -n ".")'
alias h=history
alias j=jump
alias l='ls -F'
alias ll='ls -laF'
alias o='git oneline'
alias p='git patch'
alias prettyjson='python -m json.tool'
alias oo='git oneline -10'
alias s=ssh
alias serve='python -m SimpleHTTPServer' # optional arg: port (defaults to 8000)
alias t=tmux
alias v=vim


#
# Suffix aliases
# (eg. "foo.md" to open Markdown files in "Marked 2.app")
#
#alias -s md='open -a "Marked 2.app"'

#
# Global aliases
# (work at any position within the command line)
#

## Mnemonic: "[C]lip"
#alias -g C="|clip"

## Mnemonic: "[G]rep"
#alias -g G="|grep"

## Mnemonic: "[H]ead"
#alias -g H="|head"

## Pretty-print JSON.
## Mnemonic: "[J]SON"
#alias -g J="|python -m json.tool"

## Mnemonic: "[L]ess"
#alias -g L="|less"

## Mnemonic: "[R]eset"
#alias -g R=";clear;test -n "$TMUX" && tmux clear-history;"

## Mnemonic: "[W]c"
#alias -g W="|wc -l"



stty -ixon # Disable ctrl-s and ctrl-q
#shopt -s autocd # Allows you to cd to a dir just by typing the dir name
#shopt -s checkwinsize # Line wrap on window resize

pathapp $HOME/bin/lennartcl-gitl
pathapp $HOME/.local/bin
pathapp $HOME/.gem/ruby/2.3.0/bin
pathapp $HOME/.opam/system/bin

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

[ -f "$HOME/.secrets" ] && source "$HOME/.secrets"
[[ -b "/dev/sr0" ]] && alias eject="eject -T /dev/sr0"


