#!/usr/bin/env sh
# A general, all-purpose extraction script.
#
# Default behavior: Extract archive into new directory
# Behavior with `-c` option: Extract contents into current directory

while getopts "hc" o; do case "${o}" in
	c) extracthere="True" ;;
	*) printf "Options:\\n   -c: Extract archive into current directory rather than a new one.\\n" && exit ;;
esac done

if [ -z "$extracthere" ]; then
	archive="$(readlink -f "$*")" &&
	directory="$(echo "$archive" | sed 's/\.[^\/.]*$//')" &&
	mkdir -p "$directory" &&
	cd "$directory" || exit
else
	archive="$(readlink -f "$(echo "$*" | cut -d' ' -f2)")"
fi

[ "$archive" = "" ] && printf "Give archive to extract as argument.\\n" && exit

if [ -f "$archive" ] ; then
	case "$archive" in
		*.tar.bz2|*.tar.xz|*.tbz2) tar xvjf "$archive" ;;
		*.tar.gz|*.tgz) tar xvzf "$archive" ;;
		*.lzma) unlzma "$archive" ;;
		*.bz2) bunzip2 "$archive" ;;
		*.rar) unrar x -ad "$archive" ;;
		*.gz) gunzip "$archive" ;;
		*.tar) tar xvf "$archive" ;;
		*.zip) unzip "$archive" ;;
		*.Z) uncompress "$archive" ;;
		*.7z) 7z x "$archive" ;;
		*.xz) unxz "$archive" ;;
		*.exe) cabextract "$archive" ;;
		*) printf "extract: '%s' - unknown archive method\\n" "$archive" ;;
	esac
else
	printf "File \"%s\" not found.\\n" "$archive"
fi

#extract () {
#  if [ -f $1 ] ; then
#    case $1 in
#      *.tar.bz2)   tar xvjf $1    ;;
#      *.tar.gz)    tar xvzf $1    ;;
#      *.bz2)       bunzip2 $1     ;;
#      *.rar)       rar x $1       ;;
#      *.gz)        gunzip $1      ;;
#      *.tar)       tar xvf $1     ;;
#      *.tgz)       tar xvzf $1    ;;
#      *.tbz2)      tar xvjf $1    ;;
#      *.tbz)       tar xvjf $1    ;;
#      *.zip)       unzip $1       ;;
#      *.Z)         uncompress $1  ;;
#      *.7z)        7z x $1        ;;
#      *)           echo "don't know how to extract '$1'..." ;;
#    esac
#  else
#    echo "'$1' is not a valid file!"
#  fi
#}
#if [ -f "$1" ] ; then
#  case "$1" in
#    *.tar.bz2) tar xvjf "$1" ;;
#    *.tar.gz) tar xvzf "$1" ;;
#    *.tar.xz) tar xvJf "$1" ;;
#    *.lzma) unlzma "$1" ;;
#    *.bz2) bunzip2 "$1" ;;
#    *.rar) unrar x -ad "$1" ;;
#    *.gz) gunzip "$1" ;;
#    *.tar) tar xvf "$1" ;;
#    *.tbz2) tar xvjf "$1" ;;
#    *.tgz) tar xvzf "$1" ;;
#    *.zip) unzip "$1" ;;
#    *.Z) uncompress "$1" ;;
#    *.7z) 7z x "$1" ;;
#    *.xz) unxz "$1" ;;
#    *.exe) cabextract "$1" ;;
#    *) echo "extract: '$1' - unknown archive method" ;;
#  esac
#else
#    echo "$1 - file does not exist"
#fi



