#!/bin/sh

file=`dirname $0`

#sudo apt update
#installx build-essential unzip 
#installx python3-pip
#installx libgconf-2-4
#installx rodeo
#installx gfortran-7
#installx libatlas-dev g++
#installx ipython

apt-cache pkgnames python3- | sed 's/python3-//g' | sed -z 's/enum\n//g' | sed -z 's/typing-extensions\n//g' | sort -r > requirements.txt
#cat requirements.txt | while read PACKAGE; do python3 -m pip install "$PACKAGE"; echo "-->> $PACKAGE"; done
cat requirements.txt | parallel -P 200 python3 -m pip install {}

#installx $(apt-cache pkgnames python3- | grep -Fvx -f $file/python3.txt)
#installx $(apt-cache pkgnames python- | grep -Fvx -f $file/python.txt)





##Scikit-learn
#sudo pip install -U scikit-learn
#installx build-essential python-dev python-numpy python-numpy-dev python-scipy libatlas-dev g++ python-matplotlib ipython
#installx build-essential python3-dev python3-numpy python3-numpy-dev python3-scipy libatlas-dev g++ python3-matplotlib ipython

##Jupiter
#sudo apt update

# python-scipy python-h5py python-dev  python-numpy python-matplotlib

#sudo pip install jupyter
##Tanserflow
#sudo pip3 install celery tensorflow keras matplotlib numpy sklearn
##Sentillo
#sudo pip install --upgrade pip
#sudo pip install paho-mqtt
#sudo pip install pyserial
#sudo pip install networkx
#sudo pip install neurolab
#sudo pip3 install -I urlscan
#sudo pip install -I urlscan
#sudo pip install tensorflow
#sudo pip3 install black



