#!/bin/sh

directory=$TOOLSPATH/sdn

mkdir -p $directory
cd $directory
#SDN
	# attention: python-magic
	cd $directory
	# Sdn-wise java
	git clone git://github.com/sdnwiselab/sdn-wise-java
	git clone git://github.com/sdnwiselab/onos
	git clone git://github.com/mininet/mininet
	# Application: Downlad Apache Karaf
	mkdir $directory/Applications
	wget http://archive.apache.org/dist/karaf/3.0.2/apache-karaf-3.0.2.tar.gz -P $directory/Applications
	tar -zxvf $directory/Applications/apache-karaf-3.0.2.tar.gz -C $directory/Applications/
	# Add ONOS and SDN-WISE to Karaf
	sed -i '/featuresRepositories=mvn:org.apache.karaf.features\/standard\/3.0.2\/xml\/features,mvn:org.apache.karaf.features\/enterprise\/3.0.2\/xml\/features,mvn:org.ops4j.pax.web\/pax-web-features\/3.1.2\/xml\/features,mvn:org.apache.karaf.features\/spring\/3.0.2\/xml\/features/c\featuresRepositories=mvn:org.apache.karaf.features\/standard\/3.0.2\/xml\/features,mvn:org.apache.karaf.features\/enterprise\/3.0.2\/xml\/features,mvn:org.ops4j.pax.web\/pax-web-features\/3.1.2\/xml\/features,mvn:org.apache.karaf.features\/spring\/3.0.2\/xml\/features,mvn:org.onosproject\/onos-features\/1.0.2-SNAPSHOT\/xml\/features' $directory/Applications/apache-karaf-3.0.2/etc/org.apache.karaf.features.cfg
	sed -i '/featuresBoot=config,standard,region,package,kar,ssh,management/c\featuresBoot=config,standard,region,package,kar,ssh,management,onos-api,onos-core-trivial,onos-cli,onos-openflow,onos-app-fwd,onos-app-mobility,onos-gui,onos-sdnwise,onos-sdnwise-providers' $directory/Applications/apache-karaf-3.0.2/etc/org.apache.karaf.features.cfg
	# Setup environment variables
	echo "export ONOS_ROOT=$directory/onos" >> ~/.bashrc
	source ~/.bashrc
	source $ONOS_ROOT/tools/dev/bash_profile
	# Mininet
	sudo mininet/util/install.sh -nfv
	# Onos
	cd $directory/onos
	sudo tools/build/onos-buck build onos --show-output 
	#tools/build/onos-buck run onos-local -- clean debug

