#!/bin/bash
mypath=`realpath "$@"`
directory=`dirname "$mypath"`
file=`basename "$@"`
filename="${file%.*}"
#cd "$directory"

#bibtool --  'add.field{title="\href{%s(url)}{%s(title)}"}' src/main.bib -o src/.main.bib
#export MANPATH=$MANPATH:/home/aghiles/aghiles/Software/texlive/2018/texmf-dist/doc/man
#export INFOPATH=$INFOPATH:/home/aghiles/aghiles/Software/texlive/2018/texmf-dist/doc/info
#export PATH=/home/aghiles/aghiles/Software/texlive/2018/bin/x86_64-linux:$PATH

PS3='Please enter your choice: '
options=("These" "Paper" "Slide" "Poster" "Draft" "Plot")

select opt in "${options[@]}"
do
    case $opt in
        "These")
            latexmk -f -cd -pvc -jobname=these "$@"
            ;;
        "Paper")
            latexmk -f -cd -pvc -jobname=paper "$@"
            ;;
        "Slide")
            latexmk -f -cd -pvc -jobname=slide "$@"
            ;;
        "Poster")
            latexmk -f -cd -pvc -jobname=poster "$@"
            ;;
        "Draft")
            latexmk -f -cd -pvc -jobname=draft "$@"
            ;;
        "Plot")
            latexmk -f -cd -pvc -jobname=$filename "$@"
            ;;
        *) echo "invalid option $REPLY";;
    esac
done



#latexmk -f -cd -lualatex -output-directory=bin -jobname=$filename $filename.tex
#evince bin/$filename.pdf

