#!/bin/bash

[[ "$1" == *.tex ]] || exit

file=$(readlink -f "$1")
dir=$(dirname "$file")
base="${file%.*}"

rm -rf $dir/_minted-main
find "$dir"  -maxdepth 1 -type f -regextype gnu-awk -regex "^$base\.(4tc|xref|tmp|pyc|pyo|fls|vrb|fdb_latexmk|bak|swp|aux|log|synctex\(busy\)|lof|nav|out|snm|toc|tdo|bcf|run\.xml|synctex\.gz|blg|bbl|glo|glg|gls|ist)" -delete

#case "$1" in
#	*.tex)
#	file=$(readlink -f "$1")
#	dir=$(dirname "$file")
#	base="${file%.*}"
#	find "$dir"  -maxdepth 1 -type f -regextype gnu-awk -regex "^$base\\.(4tc|xref|tmp|pyc|pyo|fls|vrb|fdb_latexmk|bak|swp|aux|log|synctex\\(busy\\)|lof|lot|maf|idx|mtc|mtc0|nav|out|snm|toc|bcf|run\\.xml|synctex\\.gz|blg|bbl)" -delete ;;
#	*) printf "Give .tex file as argument.\\n" ;;
#esac
