#!/bin/bash

INSTANCE=$1
COMMAND=$2

if ! xdotool search --classname "$INSTANCE" > /dev/null; then
  i3-msg "exec $TERMINAL --name=$INSTANCE -e 'i3-runner \"$COMMAND\"'"
  sleep .8
fi

i3-msg "[instance="$INSTANCE"] scratchpad show; [instance="$INSTANCE"] move position center"
