#!/bin/bash

gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "[
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom9/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom10/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom11/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom12/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom13/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom14/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom15/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom16/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom17/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom18/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom19/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom20/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom21/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom22/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom23/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom24/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom25/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom26/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom27/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom28/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom29/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom30/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom31/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom32/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom33/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom34/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom35/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom36/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom37/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom38/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom39/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom40/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom41/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom42/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom43/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom44/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom45/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom46/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom47/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom48/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom49/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom50/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom51/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom52/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom53/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom54/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom55/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom56/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom57/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom58/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom59/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom60/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom61/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom62/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom63/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom64/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom65/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom66/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom67/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom68/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom69/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom70/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom71/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom72/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom73/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom74/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom75/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom76/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom77/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom78/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom79/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom80/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom81/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom82/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom83/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom84/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom85/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom86/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom87/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom88/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom89/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom90/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom91/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom92/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom93/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom94/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom95/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom96/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom97/',
	'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom98/'
]"

gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom94/ name 'Screenshot'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom94/ command 'gnome-screenshot -i'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom94/ binding '<Super><Alt>Print'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom97/ name 'Terminal'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom97/ command 'gnome-terminal'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom97/ binding '<Primary><Alt>t'


gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name 'pa1'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/pa-*/1*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding '<Primary><Alt>ampersand'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ name 'pa2'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/pa-*/2*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ binding '<Primary><Alt>eacute'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ name 'pa3'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/pa-*/3*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ binding '<Primary><Alt>quotedbl'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/ name 'pa4'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/pa-*/4*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/ binding '<Primary><Alt>apostrophe'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/ name 'pa5'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/pa-*/5*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/ binding '<Primary><Alt>parenleft'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/ name 'pa6'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/pa-*/6*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/ binding '<Primary><Alt>minus'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/ name 'pa7'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/pa-*/7*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/ binding '<Primary><Alt>egrave'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/ name 'pa8'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/pa-*/8*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/ binding '<Primary><Alt>underscore'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/ name 'pa9'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/pa-*/9*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/ binding '<Primary><Alt>ccedilla'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom9/ name 'pa0'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom9/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/pa-*/0*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom9/ binding '<Primary><Alt>agrave'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom95/ name 'pa10'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom95/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/pa-*/)*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom95/ binding '<Primary><Alt>parenright'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom96/ name 'pa11'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom96/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/pa-*/=*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom96/ binding '<Primary><Alt>equal'







gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom10/ name 'p1'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom10/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/p-*/1*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom10/ binding '<Primary>ampersand'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom11/ name 'p2'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom11/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/p-*/2*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom11/ binding '<Primary>eacute'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom12/ name 'p3'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom12/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/p-*/3*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom12/ binding '<Primary>quotedbl'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom13/ name 'p4'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom13/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/p-*/4*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom13/ binding '<Primary>apostrophe'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom14/ name 'p5'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom14/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/p-*/5*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom14/ binding '<Primary>parenleft'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom15/ name 'p6'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom15/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/p-*/6*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom15/ binding '<Primary>minus'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom16/ name 'p7'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom16/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/p-*/7*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom16/ binding '<Primary>egrave'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom17/ name 'p8'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom17/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/p-*/8*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom17/ binding '<Primary>underscore'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom18/ name 'p9'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom18/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/p-*/9*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom18/ binding '<Primary>ccedilla'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom19/ name 'p0'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom19/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/p-*/0*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom19/ binding '<Primary>agrave'




gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom98/ name 'phoe'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom98/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ph-*/oe*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom98/ binding '<Primary><Shift>oe'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom20/ name 'ph1'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom20/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ph-*/1*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom20/ binding '<Primary><Shift>ampersand'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom21/ name 'ph2'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom21/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ph-*/2*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom21/ binding '<Primary><Shift>eacute'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom22/ name 'ph3'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom22/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ph-*/3*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom22/ binding '<Primary><Shift>quotedbl'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom23/ name 'ph4'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom23/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ph-*/4*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom23/ binding '<Primary><Shift>apostrophe'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom24/ name 'ph5'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom24/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ph-*/5*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom24/ binding '<Primary><Shift>parenleft'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom25/ name 'ph6'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom25/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ph-*/6*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom25/ binding '<Primary><Shift>minus'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom26/ name 'ph7'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom26/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ph-*/7*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom26/ binding '<Primary><Shift>egrave'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom27/ name 'ph8'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom27/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ph-*/8*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom27/ binding '<Primary><Shift>underscore'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom28/ name 'ph9'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom28/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ph-*/9*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom28/ binding '<Primary><Shift>ccedilla'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom29/ name 'ph0'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom29/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ph-*/0*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom29/ binding '<Primary><Shift>agrave'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom92/ name 'ph10'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom92/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ph-*/)*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom92/ binding '<Primary><Shift>parenright'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom93/ name 'ph11'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom93/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ph-*/=*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom93/ binding '<Primary><Shift>equal'





gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom30/ name 'a1'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom30/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/a-*/1*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom30/ binding '<Alt>ampersand'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom31/ name 'a2'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom31/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/a-*/2*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom31/ binding '<Alt>eacute'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom32/ name 'a3'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom32/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/a-*/3*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom32/ binding '<Alt>quotedbl'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom33/ name 'a4'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom33/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/a-*/4*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom33/ binding '<Alt>apostrophe'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom34/ name 'a5'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom34/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/a-*/5*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom34/ binding '<Alt>parenleft'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom35/ name 'a6'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom35/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/a-*/6*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom35/ binding '<Alt>minus'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom36/ name 'a7'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom36/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/a-*/7*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom36/ binding '<Alt>egrave'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom37/ name 'a8'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom37/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/a-*/8*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom37/ binding '<Alt>underscore'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom38/ name 'a9'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom38/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/a-*/9*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom38/ binding '<Alt>ccedilla'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom39/ name 'a0'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom39/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/a-*/0*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom39/ binding '<Alt>agrave'






gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom40/ name 's1'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom40/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/s-*/1*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom40/ binding '<Super>ampersand'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom41/ name 's2'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom41/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/s-*/2*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom41/ binding '<Super>eacute'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom42/ name 's3'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom42/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/s-*/3*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom42/ binding '<Super>quotedbl'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom43/ name 's4'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom43/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/s-*/4*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom43/ binding '<Super>apostrophe'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom44/ name 's5'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom44/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/s-*/5*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom44/ binding '<Super>parenleft'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom45/ name 's6'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom45/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/s-*/6*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom45/ binding '<Super>minus'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom46/ name 's7'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom46/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/s-*/7*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom46/ binding '<Super>egrave'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom47/ name 's8'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom47/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/s-*/8*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom47/ binding '<Super>underscore'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom48/ name 's9'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom48/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/s-*/9*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom48/ binding '<Super>ccedilla'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom49/ name 's0'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom49/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/s-*/0*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom49/ binding '<Super>agrave'





gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom50/ name 'ps1'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom50/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ps-*/1*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom50/ binding '<Primary><Super>ampersand'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom51/ name 'ps2'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom51/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ps-*/2*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom51/ binding '<Primary><Super>eacute'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom52/ name 'ps3'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom52/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ps-*/3*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom52/ binding '<Primary><Super>quotedbl'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom53/ name 'ps4'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom53/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ps-*/4*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom53/ binding '<Primary><Super>apostrophe'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom54/ name 'ps5'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom54/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ps-*/5*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom54/ binding '<Primary><Super>parenleft'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom55/ name 'ps6'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom55/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ps-*/6*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom55/ binding '<Primary><Super>minus'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom56/ name 'ps7'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom56/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ps-*/7*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom56/ binding '<Primary><Super>egrave'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom57/ name 'ps8'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom57/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ps-*/8*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom57/ binding '<Primary><Super>underscore'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom58/ name 'ps9'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom58/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ps-*/9*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom58/ binding '<Primary><Super>ccedilla'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom59/ name 'ps0'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom59/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ps-*/0*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom59/ binding '<Primary><Super>agrave'



#####"""


gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom60/ name 'hs1'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom60/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/hs-*/1*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom60/ binding '<Shift><Super>ampersand'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom61/ name 'hs2'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom61/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/hs-*/2*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom61/ binding '<Shift><Super>eacute'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom62/ name 'hs3'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom62/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/hs-*/3*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom62/ binding '<Shift><Super>quotedbl'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom63/ name 'hs4'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom63/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/hs-*/4*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom63/ binding '<Shift><Super>apostrophe'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom64/ name 'hs5'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom64/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/hs-*/5*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom64/ binding '<Shift><Super>parenleft'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom65/ name 'hs6'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom65/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/hs-*/6*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom65/ binding '<Shift><Super>minus'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom66/ name 'hs7'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom66/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/hs-*/7*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom66/ binding '<Shift><Super>egrave'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom67/ name 'lhs8'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom67/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/hs-*/8*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom67/ binding '<Shift><Super>underscore'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom68/ name 'hs9'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom68/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/hs-*/9*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom68/ binding '<Shift><Super>ccedilla'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom69/ name 'hs0'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom69/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/hs-*/0*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom69/ binding '<Shift><Super>agrave'


#######""

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom70/ name 'ha1'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom70/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ha-*/1*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom70/ binding '<Shift><Alt>ampersand'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom71/ name 'ha2'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom71/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ha-*/2*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom71/ binding '<Shift><Alt>eacute'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom72/ name 'ha3'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom72/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ha-*/3*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom72/ binding '<Shift><Alt>quotedbl'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom73/ name 'ha4'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom73/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ha-*/4*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom73/ binding '<Shift><Alt>apostrophe'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom74/ name 'ha5'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom74/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ha-*/5*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom74/ binding '<Shift><Alt>parenleft'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom75/ name 'ha6'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom75/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ha-*/6*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom75/ binding '<Shift><Alt>minus'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom76/ name 'ha7'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom76/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ha-*/7*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom76/ binding '<Shift><Alt>egrave'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom77/ name 'ha8'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom77/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ha-*/8*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom77/ binding '<Shift><Alt>underscore'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom78/ name 'ha9'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom78/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ha-*/9*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom78/ binding '<Shift><Alt>ccedilla'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom79/ name 'ha0'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom79/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/ha-*/0*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom79/ binding '<Shift><Alt>agrave'


###############

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom80/ name 'sa1'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom80/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/sa-*/1*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom80/ binding '<Super><Alt>ampersand'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom81/ name 'sa2'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom81/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/sa-*/2*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom81/ binding '<Super><Alt>eacute'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom82/ name 'sa3'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom82/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/sa-*/3*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom82/ binding '<Super><Alt>quotedbl'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom83/ name 'sa4'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom83/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/sa-*/4*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom83/ binding '<Super><Alt>apostrophe'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom84/ name 'sa5'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom84/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/sa-*/5*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom84/ binding '<Super><Alt>parenleft'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom85/ name 'sa6'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom85/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/sa-*/6*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom85/ binding '<Super><Alt>minus'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom86/ name 'sa7'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom86/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/sa-*/7*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom86/ binding '<Super><Alt>egrave'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom87/ name 'sa8'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom87/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/sa-*/8*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom87/ binding '<Super><Alt>underscore'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom88/ name 'sa9'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom88/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/sa-*/9*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom88/ binding '<Super><Alt>ccedilla'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom89/ name 'sa0'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom89/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/sa-*/0*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom89/ binding '<Super><Alt>agrave'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom90/ name 'sa10'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom90/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/sa-*/)*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom90/ binding '<Super><Alt>parenright'

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom91/ name 'sa11'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom91/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/sa-*/=*"'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom91/ binding '<Super><Alt>equal'



#gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom19/ name 'Trello'
#gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom19/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/link1'
#gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom19/ binding '<Alt>y'

#gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom20/ name 'TheLounge'
#gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom20/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/link2'
#gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom20/ binding '<Super>y'

#gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom21/ name 'Workshop'
#gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom21/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/workshop'
#gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom21/ binding '<Shift><Alt>y'

#gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom22/ name 'Run all'
#gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom22/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/run'
#gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom22/ binding '<Shift>y'




#gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom25/ name 'pkill speaker'
#gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom25/ command 'bash -ci "Aghiles/Tool/scripts/shortcuts/pkillunderscorespeaker'
#gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom25/ binding '<Super><Alt>e'


#####


###########""

#gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark
	#Adwaita-dark, Ambiance
#dconf-editor
#unity-tweak-tool
#gnome-tweaks
#gnome-control-center


#https://fsymbols.com/keyboard/linux/compose/
#Ctrl+Shift+U+code+Space

sudo setxkbmap fr
sudo loadkeys fr

lxappearance

gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['<Primary><Alt>Left']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['<Primary><Alt>Right']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "['<Primary><Alt>Up']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "['<Primary><Alt>Down']"

gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left "['<Shift><Primary><Alt>Left']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right "['<Shift><Primary><Alt>Right']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up "['<Shift><Primary><Alt>Up']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down "['<Shift><Primary><Alt>Down']"

gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-left "['<Super><Alt>Left']"
gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-right "['<Super><Alt>Right']"
gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-up "['<Super><Alt>Up']"
gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-down "['<Super><Alt>Down']"

gsettings set org.gnome.desktop.wm.keybindings move-to-corner-nw "['<Primary>Up']"
gsettings set org.gnome.desktop.wm.keybindings move-to-corner-ne "['<Primary>Down']"
gsettings set org.gnome.desktop.wm.keybindings move-to-corner-sw "['<Primary>Right']"
gsettings set org.gnome.desktop.wm.keybindings move-to-corner-se "['<Primary>Left']"
gsettings set org.gnome.desktop.wm.keybindings move-to-side-n "['<Primary><Super>Up']"
gsettings set org.gnome.desktop.wm.keybindings move-to-side-s "['<Primary><Super>Down']"
gsettings set org.gnome.desktop.wm.keybindings move-to-side-e "['<Primary><Super>Right']"
gsettings set org.gnome.desktop.wm.keybindings move-to-side-w "['<Primary><Super>Left']"


#sudo usermod -a -G dialout aghiles

sudo update-alternatives --install /usr/bin/x-www-browser x-www-browser /usr/bin/qutebrowser 30

