#!/bin/bash

IFS='
'
for arg in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
do
	gvfs-set-attribute -t 'unset' $arg 'metadata::custom-icon' 'file:///home/aghiles/Aghiles/Tool/config/icon.svg'
	fz=${arg//\/home\/aghiles\/Aghiles\//}
	ff=${fz//\//\\\/}
	sed -i "/\[0\] $ff/d" ~/.calcurse/todo
#	sed -i "s|\[0\] $arg||g" ~/Aghiles/Tool/config/office/mail/.calcurse/todo
	touch "$arg"
done

