#!/bin/sh


for arg in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
do
#	dir=`dirname $arg`
#	file=`basename $arg`

	cmd="
	compile-arduino
	arduino-exec
	arduino-log"
	
	gnome-terminal --title="$file" --command="bash -ci 'cd $dir; read usb; $cmd; $SHELL'"
done

