#!/bin/bash

for arg in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
do
	dir=`dirname $arg`
	file=`basename $arg`

	cmd="compile-ns3 $file"
	gnome-terminal --title="$filename" --command="bash -ci 'cd $dir; $cmd; $SHELL'"
done

