#!/bin/bash

mypath="$1"
directory=`dirname "$mypath"`
file=`basename "$mypath"`
extension="${file##*.}"
filename="${file%.*}"
echo $filename

cmd1="create database $filename"
sudo mysql -uroot -proot -e "$cmd1" < "$mypath"

