#!/bin/bash

tt="$1"

grep -Po -r -i ".{0,115}$1.{0,115}" */.zotero-ft-cache |  sed -r -e 's/\/.zotero-ft-cache//g' | awk -v d="$1" 'BEGIN{IGNORECASE=1}{ gsub("^........:", "\033[1;31m&\033[0m"); gsub(d, "\033[1;31m&\033[0m"); print }'
#grep -Po -r "[A-Z].*?$1.*?\." */.zotero-ft-cache |  sed -r -e 's/\/.zotero-ft-cache//g' | awk -v d="$1" 'BEGIN{IGNORECASE=1}{ gsub("^........:", "\033[1;31m&\033[0m"); gsub(d, "\033[1;31m&\033[0m"); print }'

