#!/bin/bash

perl -ne 'print "$1 $2 $3\n" while /@.*{(.*),\n*|.* +title = {(.*)},\n*|.*groups = {(.*)}/g' $1 | xargs -l echo | sed -E "s/([^ ]*) (.*) ([^ ]*)$/\3 \\\cite{\1} \2 \\\newline /g" | sort | sed -E "s/\&/\\\&/g" | sort -k1,1 -k3 | sed -E "s/#/ /g"


#perl -ne 'print "$3\n" while /@.*{(.*),\n*|.* +title = {(.*)},\n*|.*groups = {(.*)}/g' $1 | xargs -l echo | sed -E "s/([^ ]*) (.*) ([^ ]*)$/\\\textbf{\3} \\\newline \\\cite{\1} \2 \\\newline /g" | sort | uniq
#perl -ne 'print "$3\n" while /@.*{(.*),\n*|.* +title = {(.*)},\n*|.*groups = {(.*)}/g' $1 | xargs -l echo | sed -E "s/([^ ]*) (.*) ([^ ]*)$/\3 \\\cite{\1} \2 \\\newline /g" | sort | uniq



