#!/bin/bash

imagePath=~/Aghiles/Redaction*/setup/iot/storage
imageDest=~/Downloads/Pictures/tmp_image

mkdir $imageDest
# for d in *; do pdfimages -png $d/*.pdf pdfImages/$d; done
for d in $imagePath/*; do 
	filename=`basename $d`
	pdfimages -png $d/*.pdf $imageDest/$filename; 
done

cd $imageDest
find . -name "*.png" -size -1k -delete

