#!/bin/bash

	#installx nodejs
	curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
	curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
	sudo apt update


	sudo apt-key adv --keyserver keys.gnupg.net --recv-key 'E19F5F87128899B192B1A2C2AD5F960A256A04AF'
	sudo add-apt-repository 'deb http://cloud.r-project.org/bin/linux/debian buster-cran35/'
	sudo apt update


#SublimText
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list


#Virtualbox
	wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
	wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
	sudo add-apt-repository "deb http://download.virtualbox.org/virtualbox/debian buster contrib"


	sudo apt update


install-update
get-from jdk
get-from  ide
get-from tools
